server:
  port: 2001
spring:
  application:
    name: login
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 2s
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
  cloud:
    inetutils:
      default-ip-address:
eureka:
  instance:
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 20
    prefer-ip-address: true
    metadata-map:
      type: 200
      id: 1
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:1010/eureka/
step: 10